name: example-basic
on:
  push:
    branches:    
      - main
  pull_request:
jobs:

  basic-on-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress tests
        uses: ./
        with:
          working-directory: cypress/integration
          build: npx cypress info